/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ItterableApp;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Iterable<String> names = List.of("Eko", "Kurniawan", "Khannedy");
        
        for (var name: names)
            System.out.println(name);
        
    }
}
